version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  auth:
    build: ./auth
    container_name: auth
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    env_file:
      - ./auth/.env
    
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth
volumes:
  mongo-data:
